- hosts: {{ lookup ('env', 'ANSIBLE_HOSTS') }}
  become: true
  tasks:
    - name: apt update
      apt: update_cache=yes

    - name: ensure repository key is installed
      apt_key:
        id: "58118E89F3A912897C070ADBF76221572C52609D"
        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
        state: present

    - name: ensure docker registry is available
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

    - name: ensure docker and dependencies are installed
      apt:
        name: docker-engine
        update_cache: yes

    - service: name=docker state=restarted

    - name: install Nginx web server
      apt: name=nginx state=installed update_cache=true

    - name: remove default nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: install htpasswd
      apt:
        name: apache2-utils

    - name: add apt-repository for certbot
      apt_repository:
        repo: 'ppa:certbot/certbot'
        update_cache: yes

    - name: ensure certbot is installed
      apt:
        name: python-certbot-nginx
        update_cache: yes
