- hosts: devbox
  become: true
  tasks:
    - name: apt update
      apt: update_cache=yes

    - name: install Nginx web server
      apt:
        name: nginx
        state: installed
        update_cache: true

    - name: remove default nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: install htpasswd
      apt:
        name: apache2-utils

    - name: add apt-repository for certbot
      apt_repository:
        repo: 'ppa:certbot/certbot'
        update_cache: yes

    - name: ensure certbot is installed
      apt:
        name: python-certbot-nginx
        update_cache: yes
